# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-patunnel

# >> macros
%define __requires_exclude ^libpulse\.so.*$
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Send audio streams to another Pulseaudio server
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://github.com/vmatare/patunnel
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-patunnel.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   libpulse-simple.so.0(PULSE_0)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
This app allows you to load a PulseAudio tunnel sink that connects to another PulseAudio server, e.g. via WiFi. You can then route audio streams to that server, to play them back on your home stereo, for example.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
/usr/share/icons/hicolor/86x86/apps
/usr/share/applications
/usr/share/harbour-patunnel
/usr/bin
%defattr(644,root,root,755)
%{_bindir}
%attr(755,root,root) %{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/%{name}/qml
%{_datadir}/%{name}/qml/cover/CoverPage.qml
%{_datadir}/%{name}/qml/pages/PulseStreamListPage.qml
%{_datadir}/%{name}/qml/pages/PulseSinkListPage.qml
%{_datadir}/%{name}/qml/pages/PulseAddTunnelPage.qml
%{_datadir}/%{name}/qml/harbour-patunnel.qml
%{_datadir}/icons/hicolor/86x86/apps
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/applications
%{_datadir}/applications/%{name}.desktop
# >> files
# << files
